[package]
name = "tau-cpu-macros"
version = "0.1.4"
authors = ["Vladislav Melnik <vladislav.melnik@protonmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["derive", "parsing"] }
quote = "1.0"
